name: hr_management_system_package
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  dio: ^5.5.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_maps_flutter: ^2.7.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  json_serializable: ^6.8.0
  local_auth: ^2.2.0
  location: ^6.0.2
  maps_toolkit: ^3.0.0
  mockito: ^5.4.4
  pretty_dio_logger: ^1.3.1

dev_dependencies:
# flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true
